### ISSUE TITLE
SC new issue #2 :: Sample Markdown

### ISSUE THREAD

**Issue by tpchau** [githubschool/ellie-mae-2015-12-21-ghfd#20]
Sample Markdown

## Header 2 This is hedaer
- [x] item1
- [x] iteam 2

#11 
#10 

@supreetsingh26  @vanithanangunoori @Umapaleti

**Comment by supreetsingh26** [comment]
looks good

**Comment by supreetsingh26** [comment]
closing this issue now

**Comment by vbudala** [comment]
@supreetsingh26 
Reopened the issue

**Comment by vbudala** [comment]
![dtsettings](https://cloud.githubusercontent.com/assets/16380334/11938314/f12ac02a-a7ce-11e5-96b7-93e7147000ad.JPG)

**Comment by tpchau** [comment]
:shipit: 
:rocket:
