### ISSUE TITLE
Creating new Item_Training12/21

### ISSUE THREAD

**Issue by Umapaleti** [githubschool/ellie-mae-2015-12-21-ghfd#21]
## Header2
- [x] item1
- [ ] item2

please comment on #1 

@githubstudent  thoughts?

**Comment by Umapaleti** [comment]
new issue created

**Comment by zkhogyani** [comment]
- [] txt

**Comment by Umapaleti** [comment]
We support :santa:

**Comment by Umapaleti** [comment]
@vanithanangunoori 
reply
