### ISSUE TITLE
moi issue

### ISSUE THREAD

**Issue by em-sdhawale** [githubschool/ellie-mae-2015-12-21-ghfd#29]
[] item 1

**Comment by em-sdhawale** [comment]
So are issues similar to comments/email that facilitate communication? Are issues created on repository level or they could be created on artifacts level as well? Please provide some examples.

**Comment by patrickmckenna** [comment]
@em-sdhawale Thanks for your questions

> Are issues created on repository level or they could be created on artifacts level as well?

Issues are associated with a single repository. They are not versioned documents, though, i.e. they're separate from everything listed under the Code tab. Does that answer your question?

> What is the difference between issue and pull request?

We'll be covering this right after the break!

**Comment by em-sdhawale** [comment]
thank you!
